[tasks.build-linux]
script_runner = "@shell"
script = [
'''
docker run --rm -v $PWD:/usr/src/pitaya -w /usr/src/pitaya rust:1.45.0 cargo build --release
'''
]

[tasks.generate]
script_runner = "@shell"
script = [
'''
cbindgen --config cbindgen.toml --crate pitaya-rs --lang c --output pitaya.h
'''
]