[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.deps]
workspace = false
dependencies = [
    "undeps",
    "docker-compose-up",
    "run-example-server",
]

[tasks.undeps]
workspace = false
dependencies = [
    "stop-example-server",
    "docker-compose-down",
]

[tasks.docker-compose-up]
workspace = false
private = true
command = "docker-compose"
args = ["up", "-d"]

[tasks.docker-compose-down]
workspace = false
private = true
command = "docker-compose"
args = ["down"]

[tasks.ensure-example-server-bin]
workspace = false
private = true
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
go build main.go
'''
]

[taks.clippy]
workspace = false
script = [
'''
cargo clippy --all --tests
'''
]

[tasks.run-example-server]
workspace = false
private = true
dependencies = [
    "ensure-example-server-bin",
    "stop-example-server"
]
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
./main --port 3251 --type room --frontend=false > output.log 2>&1 &
echo $! > example-pitaya-server.pid
'''
]

[tasks.stop-example-server]
workspace = false
private = true
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
if [[ -f example-pitaya-server.pid ]]; then
    kill -TERM $(cat example-pitaya-server.pid) || true
    rm example-pitaya-server.pid
fi
rm -f output.log
'''
]
