[tasks.deps]
dependencies = [
    "undeps",
    "docker-compose-up",
    "run-example-server",
]
[tasks.build-linux]
script_runner = "@shell"
script = [
'''
docker run --rm -v $PWD:/usr/src/pitaya -w /usr/src/pitaya rust:1.45.0 cargo build --release
'''
]

[tasks.undeps]
dependencies = [
    "stop-example-server",
    "docker-compose-down",
]

[tasks.docker-compose-up]
private = true
command = "docker-compose"
args = ["up", "-d"]

[tasks.docker-compose-down]
private = true
command = "docker-compose"
args = ["down"]

[tasks.ensure-example-server-bin]
private = true
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
go build main.go
'''
]

[tasks.run-example-server]
private = true
dependencies = [
    "ensure-example-server-bin",
    "stop-example-server"
]
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
./main --port 3251 --type room --frontend=false > output.log 2>&1 &
echo $! > example-pitaya-server.pid
'''
]

[tasks.stop-example-server]
private = true
script_runner = "@shell"
script = [
'''
cd example-pitaya-server
if [[ -f example-pitaya-server.pid ]]; then
    kill -TERM $(cat example-pitaya-server.pid) || true
    rm example-pitaya-server.pid
fi
rm -f output.log
'''
]

[tasks.generate]
script_runner = "@shell"
script = [
'''
cbindgen --config cbindgen.toml --crate pitaya-rs --lang c --output pitaya.h
'''
]
