[package]
name = "test_helpers"
version = "0.1.0"
authors = ["Leonardo Hahn <leonardo.hahn@tfgco.com>"]
edition = "2018"

[dependencies]
slog = { version = "2.5", features = ["max_level_trace"] }
slog-json = "2.3"
slog-term = "2.6.0"
slog-async = "2.5.0"